### ISSUE TITLE
has been compiled by a more recent version of the Java Runtime (class file version 53.0)

### ISSUE THREAD

**Issue by tokazio** [forax/beautiful_logger#4]
Salut,

J'ai assisté à ta super conf devoxx 2018 sur le logger.
Du coup j'ai voulu l'essayer.
Avec java 8:
```
... has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
Il semblerait qu'il soit compilé en java 9.
Je n'ai pas réussi à builder (je suis sous windows + l'extraction du tar.gz ne m'est pas autorisée)

Où puis'je trouver une version pour java 8?

Merci.

**Comment by forax** [comment]
Ok, je pense que j'ai ma petite idée de pourquoi,
juste pour confirmer, tu peux me donner le nom de la classe qui merde ?

**Comment by forax** [comment]
La dernière version (0.9.8) devrait avoir fixer les différents bugs que j'ai stupidement introduit en ajoutant le support de la version 11 (entre autre).

Est-ce que tu peux vérifier que cela marche de ton coté ?

**Comment by tokazio** [comment]
Message d'origine:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: Unsupported class file version 53.0, this version of the Java Runtime only recognizes class file versions up to 52.0
	at sun.misc.Unsafe.defineAnonymousClass(Native Method)
	at com.github.forax.beautifullogger.LoggerImpl.loggerClass(LoggerImpl.java:509)
	at com.github.forax.beautifullogger.LoggerImpl.<clinit>(LoggerImpl.java:502)
	at com.github.forax.beautifullogger.LoggerConfig.fromClass(LoggerConfig.java:243)
	at com.github.forax.beautifullogger.LoggerConfig.fromClass(LoggerConfig.java:233)
	at com.esyo.sharedesk.channels.ScreenServerApp.<init>(ScreenServerApp.java:126)
	at com.esyo.sharedesk.channels.ScreenServerApp.main(ScreenServerApp.java:36)
```
ok en 0.9.8, MERCI !
